# -*- coding: utf-8 -*-
"""fix_guyzss_hitdefattr.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xw3Wh4DqDBIwFj0nq3-PTO8VEtkEdBwg
"""

#!/usr/bin/env python3
# Save as fix_guyzss_hitdefattr.py and run:
# python fix_guyzss_hitdefattr.py /path/to/guyzss.zss
import sys, re, pathlib

if len(sys.argv) < 2:
    print("Usage: python fix_guyzss_hitdefattr.py /path/to/guyzss.zss")
    sys.exit(1)

inp_path = pathlib.Path(sys.argv[1])
if not inp_path.exists():
    print("Input file not found:", inp_path)
    sys.exit(2)

text = inp_path.read_text(encoding='utf-8', errors='ignore')

# 1) Replace occurrences like: hitdefattr = A, B  -> hitdefattr = A && B
pattern = re.compile(r'(hitdefattr\s*=\s*)([A-Za-z0-9_]+)\s*,\s*([A-Za-z0-9_]+)')
replacements = 0
while True:
    text, n = pattern.subn(r'\1\2 && \3', text)
    if n == 0:
        break
    replacements += n

# 2) If there are cases with three or more attributes separated by commas, iteratively convert the remaining commas
# e.g. hitdefattr = A, B, C  -> A && B && C
pattern_multi = re.compile(r'(hitdefattr\s*=\s*)([A-Za-z0-9_]+(?:\s*&&\s*[A-Za-z0-9_]+)*)(\s*,\s*[A-Za-z0-9_]+)')
while True:
    def repl(m):
        head = m.group(1)
        existing = m.group(2)
        tail = m.group(3)
        return head + existing + re.sub(r'^\s*,\s*', ' && ', tail)
    text, n = pattern_multi.subn(repl, text)
    if n == 0:
        break
    replacements += n

# Write output
out_path = inp_path.with_name(inp_path.stem + "_fixed" + inp_path.suffix)
out_path.write_text(text, encoding='utf-8')

# Show summary
# List hitdef lines before/after to allow quick inspection
orig_lines = inp_path.read_text(encoding='utf-8', errors='ignore').splitlines()
new_lines = text.splitlines()
before = [(i+1, l.strip()) for i, l in enumerate(orig_lines) if 'hitdefattr' in l]
after = [(i+1, l.strip()) for i, l in enumerate(new_lines) if 'hitdefattr' in l]

print("Input file:", inp_path)
print("Output file:", out_path)
print("Replacements made (approx):", replacements)
print("hitdefattr lines before:", len(before))
print("hitdefattr lines after: ", len(after))
print("\nSample BEFORE (first 10 lines containing hitdefattr):")
for ln, txt in before[:10]:
    print(f"{ln}: {txt}")
print("\nSample AFTER (first 10 lines containing hitdefattr):")
for ln, txt in after[:10]:
    print(f"{ln}: {txt}")

print("\nDone. Please open", out_path, "and run Ikemen GO to confirm there are no further parser errors.")